import Foundation

public enum RoleMap {
    public static let axToCanonical: [String: CanonicalRole] = [
        "AXApplication": .application,
        "AXWindow": .window,
        "AXSheet": .dialog,
        "AXDialog": .dialog,
        "AXDocument": .document,
        "AXGroup": .group,
        "AXLayoutArea": .region,
        "AXLandmarkBanner": .banner,
        "AXLandmarkContentInfo": .contentinfo,
        "AXLandmarkNavigation": .navigation,
        "AXLandmarkMain": .main,
        "AXLandmarkComplementary": .complementary,
        "AXLandmarkSearch": .search,
        "AXLandmarkForm": .form,
        "AXHeading": .heading,
        "AXStaticText": .paragraph,
        "AXLink": .link,
        "AXButton": .button,
        "AXToggle": .toggleButton,
        "AXMenuButton": .menuButton,
        "AXPopUpButton": .menuButton,
        "AXSplitButton": .splitButton,
        "AXCheckBox": .checkbox,
        "AXRadioButton": .radioButton,
        "AXSwitch": .switch,
        "AXTextField": .textbox,
        "AXSearchField": .searchbox,
        "AXTextArea": .editor,
        "AXSecureTextField": .password,
        "AXComboBox": .combobox,
        "AXListBox": .listbox,
        "AXList": .list,
        "AXListItem": .listitem,
        "AXOutline": .tree,
        "AXOutlineRow": .treeitem,
        "AXTable": .table,
        "AXRow": .row,
        "AXCell": .cell,
        "AXColumn": .columnHeader,
        "AXRowHeader": .rowHeader,
        "AXTab": .tab,
        "AXTabPanel": .tabPanel,
        "AXTabGroup": .tabList,
        "AXMenu": .menu,
        "AXMenuItem": .menuItem,
        "AXMenuItemMarkChar": .menuItemCheckbox,
        "AXMenuItemCmdChar": .menuItemRadio,
        "AXToolbar": .toolbar,
        "AXSplitter": .separator,
        "AXProgressIndicator": .progress,
        "AXSlider": .slider,
        "AXIncrementor": .spinButton,
        "AXScrollBar": .scrollbar,
        "AXImage": .image,
        "AXIcon": .icon,
        "AXFigure": .figure,
        "AXHelpTag": .tooltip,
        "AXStatusItem": .status,
        "AXSystemDialog": .alert,
        "AXLog": .log,
        "AXMarquee": .marquee,
        "AXTimer": .timer,
        "AXUnknown": .unknown
    ]

    public static func canonicalRole(for axRole: String?) -> CanonicalRole {
        guard let axRole else { return .unknown }
        return axToCanonical[axRole] ?? .unknown
    }
}
